# Generated by Django 2.0.5 on 2018-10-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'URL表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='userinfotorole',
            options={'verbose_name_plural': '用户分配角色表'},
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='permission',
            name='url',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
