# Generated by Django 2.0.5 on 2018-10-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181005_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': '操作表'},
        ),
        migrations.AddField(
            model_name='action',
            name='code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
